#!/bin/sh -x
if [[ $1 == "" ]]; then
	echo "no input file"
	exit
fi
./converter/build/converter < $1 > out
if [[ $2 == "" ]]; then
	processing-java --sketch=`pwd`/chord_visualizer/ --run `pwd`/out
else
	processing-java --sketch=`pwd`/chord_visualizer/ --run `pwd`/out `pwd`/$2
fi
